# Generated by Django 4.0.4 on 2022-07-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categories_remove_contact_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.IntegerField()),
                ('instagram', models.IntegerField()),
                ('twitter', models.IntegerField()),
                ('youtube', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='Banner',
        ),
    ]
