# Generated by Django 4.0.4 on 2022-07-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_activevideo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveVideo',
            new_name='Active_video',
        ),
    ]
