# Generated by Django 4.0.4 on 2022-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_about_us_followers_link_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.TextField(max_length=800)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
