# Generated by Django 4.0.4 on 2022-07-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_trendingarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='title',
        ),
        migrations.AddField(
            model_name='about_us',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='paragraph',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
