# Generated by Django 4.0.4 on 2022-07-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_about_us_title_about_us_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='paragraph',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
