# Generated by Django 3.2.12 on 2022-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_about_us_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='poster',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
