# Generated by Django 3.2.12 on 2022-07-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220717_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
