# Generated by Django 3.2.12 on 2022-07-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_trendtop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=300)),
                ('quote', models.TextField(max_length=500)),
            ],
        ),
    ]
